<?php /* Smarty version 2.6.10, created on 2018-12-10 13:51:45
         compiled from Main.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%8B^8BA^8BAC94BE%%Main.tpl.inc'] = '32343aed23500f492ffdfb8e46e4be66';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemV'), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/resources/css/ext-all.css"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/main1.css"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/adapter/ext/ext-base.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ext-all.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/TabCloseMenu.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/thickbox/thickbox.css"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_9(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/ymPrompt.js"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_10(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/skin/qq/ymPrompt.css"), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_11(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemV'), $_smarty);
}


function _smarty_tplfunc_32343aed23500f492ffdfb8e46e4be66_12(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Servtel'), $_smarty);
}



?>
