<?php /* Smarty version 2.6.10, created on 2018-12-10 13:52:01
         compiled from Cangku/Chengpin/MadanRukuJs.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%A7^A78^A783EE72%%MadanRukuJs.tpl.inc'] = '03e92fe3ed50cb237d2cb2bd2b322b49';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Cangku/Chengpin/MadanRukuJs.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_03e92fe3ed50cb237d2cb2bd2b322b49_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.json.js"), $_smarty);
}



?>
