<?php /* Smarty version 2.6.10, created on 2018-12-10 13:51:58
         compiled from Main2Son/_jsCommon.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D3^D3B^D3B46A51%%_jsCommon.tpl.inc'] = '1dc98eaf3a86baf237a470cbfa4c1199';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main2Son/_jsCommon.tpl', 8, false),array('modifier', 'json_encode', 'Main2Son/_jsCommon.tpl', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_1dc98eaf3a86baf237a470cbfa4c1199_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/layer/layer.js"), $_smarty);
}



?>
