<?php /* Smarty version 2.6.10, created on 2018-12-10 13:51:49
         compiled from Search/huaxing.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D8^D8D^D8D4B390%%huaxing.tpl.inc'] = 'e091380054c22e2a72267a7440ef173a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Search/huaxing.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_e091380054c22e2a72267a7440ef173a_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}


function _smarty_tplfunc_e091380054c22e2a72267a7440ef173a_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}



?>
